ui <- fluidPage(theme = shinytheme("slate"),
                useShinyalert(),
                br(),
                sidebarPanel(selectInput("method", 
                                         label = "Select TES calculation method",
                                         choices = list("Weighted two-sample Kolmogorov-Smirnov test", 
                                                        "Density ratio of RCB scores from two treatments",
                                                        "Density difference of RCB scores from two treatments"),
                                         selected = "Weighted two-sample Kolmogorov-Smirnov test"),
                             tags$div(title=inf_name, textInput("control_name", 
                                                                "Name of the treatment (optional)", "control")),
                             tags$div(title=inf_file, fileInput(inputId = "control_file",
                                                                label = "Upload the RCB scores from control treatment",
                                                                accept = c(".txt"))),
                             tags$div(title=inf_name, textInput("exp_name", 
                                                                "Name of the treatment (optional)", "experimental")),
                             tags$div(title=inf_file, fileInput(inputId = "exp_file",
                                                                label = "Upload the RCB scores from experimental treatment",
                                                                accept = c(".txt"))),
                             tags$div(title=exemp, checkboxInput(inputId = "exemplary_files",
                                                                 label = "Use exemplary data instead")),
                             tags$div(title="Choose the folder to save the plots and results",
                                      shinyDirButton("dir", "Save to", "Choose the folder")),
                             verbatimTextOutput("dir", placeholder = TRUE),
                             actionButton(inputId = "up_df",
                                          label = "Update data"),
                             actionButton(inputId = "generate_plot",
                                          label = "Calculate"), br(),
                             column(1, HTML(paste0("N",tags$sub("control"), ": "))),  
                             column(2, textOutput("ncontrol"), offset=1), br(),
                             column(1, HTML(paste0("N",tags$sub("experimental"), ": "))), 
                             column(2, textOutput("nexp"), offset=1), br()
                ),
                mainPanel(tabsetPanel(
                  tabPanel("The data", br(), h4("Datasets to compare"),
                           column(1, tableOutput("ccontents")), column(2, tableOutput("econtents"))
                  ),
                  tabPanel("The plot", textOutput("nexp1"))
                ))
)